### PR TITLE
develop-Bug-Better-management-of-refunds

### PR DESCRIPTION
**Pull request by NiklasHogefjord**
* Adds support for using Avardas refund logic (refund/release the reserved amount before the payment is captured).
* Specify quantity on order lines sent to Avarda.

### CODE REVIEW

**Comment by NiklasHogefjord** [comment]
Task linked: [CU-3jv12ck Bug: Better management of refunds](https://app.clickup.com/t/3jv12ck)

**Comment by NiklasHogefjord** [comment]
This should now handle refund of order lines + also refund part of the original order line price **if** the quantity is 1.

**Comment by NiklasHogefjord** [comment]
We now send refunded items in the activate request, but as negative order lines.

**Review by MichaelBengtsson — APPROVED** [review]
Technically `classes/class-aco-api.php::133` method `request_refund_order` has a incorrect block comment. But nothing major.

**Pull request merged**
